# Generated by Django 4.2.5 on 2023-09-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_reservation_date_booking_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
